In [15]:
import pandas as pd
import numpy as np
from datetime import date 
import pandas_datareader.data as web
import os
import time
!pip install nsepy

Requirement already satisfied: nsepy in c:\users\chamu\anacondaprojects\lib\site-packages (0.7)
Requirement already satisfied: beautifulsoup4 in c:\users\chamu\anacondaprojects\lib\site-packages (from nsepy) (4.6.0)
Requirement already satisfied: numpy in c:\users\chamu\anacondaprojects\lib\site-packages (from nsepy) (1.14.0)
Requirement already satisfied: pandas in c:\users\chamu\anacondaprojects\lib\site-packages (from nsepy) (0.22.0)
Requirement already satisfied: click in c:\users\chamu\anacondaprojects\lib\site-packages (from nsepy) (6.7)
Requirement already satisfied: six in c:\users\chamu\anacondaprojects\lib\site-packages (from nsepy) (1.11.0)
Requirement already satisfied: requests in c:\users\chamu\anacondaprojects\lib\site-packages (from nsepy) (2.18.4)
Requirement already satisfied: python-dateutil>=2 in c:\users\chamu\anacondaprojects\lib\site-packages (from pandas->nsepy) (2.6.1)
Requirement already satisfied: pytz>=2011k in c:\users\chamu\anacondaprojects\lib\site-packages (from pandas->nsepy) (2017.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\chamu\anacondaprojects\lib\site-packages (from requests->nsepy) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\chamu\anacondaprojects\lib\site-packages (from requests->nsepy) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\chamu\anacondaprojects\lib\site-packages (from requests->nsepy) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\chamu\anacondaprojects\lib\site-packages (from requests->nsepy) (2018.1.18)

notebook 5.4.0 requires ipykernel, which is not installed.
jupyter 1.0.0 requires ipykernel, which is not installed.
jupyter-console 5.2.0 requires ipykernel, which is not installed.
ipywidgets 7.1.1 requires ipykernel>=4.5.1, which is not installed.

In [16]:
from nsepy import get_history
%pwd

'C:\\Users\\chamu\\Desktop\\Github'

In [17]:
df_list = pd.read_csv('list.csv',header= None)
names = list(df_list.values.flatten())

In [18]:
names

['SBIN', 'HDFC', 'HDFCBANK']

In [19]:
df=pd.DataFrame()
for i in range(len(names)):
    a = (names[i])
    try:
        df = get_history(symbol=a, start=date(2005,1,1), end=date(2018,1,1))
        df = df.append(df)
        print(i) #can remove this line, just prints the index for the list of names
    except:
        df = df

0
1
2

In [20]:
df

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2005-01-03,HDFCBANK,EQ,520.35,516.05,527.80,516.05,526.00,525.25,524.22,129558,6.791704e+12,NaN,79205,0.6113
2005-01-04,HDFCBANK,EQ,525.25,525.05,531.00,505.00,520.90,519.45,523.22,223806,1.170999e+13,NaN,137539,0.6145
2005-01-05,HDFCBANK,EQ,519.45,520.00,520.00,487.00,497.00,500.05,505.04,398787,2.014022e+13,NaN,210404,0.5276
2005-01-06,HDFCBANK,EQ,500.05,500.05,509.80,479.00,489.00,485.15,489.22,482951,2.362691e+13,NaN,303243,0.6279
2005-01-07,HDFCBANK,EQ,485.15,488.00,493.75,484.50,490.10,490.25,489.34,264900,1.296251e+13,NaN,138706,0.5236
2005-01-10,HDFCBANK,EQ,490.25,500.00,508.00,485.25,487.40,489.75,499.41,661287,3.302539e+13,NaN,330653,0.5000
2005-01-11,HDFCBANK,EQ,489.75,490.00,491.75,480.00,484.00,483.40,483.86,239111,1.156973e+13,NaN,131862,0.5515
2005-01-12,HDFCBANK,EQ,483.40,483.40,486.90,475.10,479.00,480.95,480.76,141879,6.820921e+12,NaN,60968,0.4297
2005-01-13,HDFCBANK,EQ,480.95,480.00,508.00,480.00,498.00,498.90,499.17,539592,2.693475e+13,NaN,327980,0.6078
2005-01-14,HDFCBANK,EQ,498.90,499.00,522.00,492.25,516.00,514.95,512.22,795192,4.073167e+13,NaN,507172,0.6378
2005-01-17,HDFCBANK,EQ,514.95,520.00,529.00,508.15,521.10,520.05,515.82,474179,2.445896e+13,NaN,260967,0.5504
2005-01-18,HDFCBANK,EQ,520.05,527.90,527.90,500.00,511.95,513.55,512.64,500006,2.563210e+13,NaN,324496,0.6490
2005-01-19,HDFCBANK,EQ,513.55,517.70,525.00,509.55,516.00,518.90,518.35,451746,2.341635e+13,NaN,322367,0.7136
2005-01-20,HDFCBANK,EQ,518.90,511.00,521.00,500.00,500.00,511.35,511.76,1090807,5.582326e+13,NaN,924734,0.8478
2005-01-24,HDFCBANK,EQ,511.35,513.90,513.90,486.00,486.00,491.35,493.63,839776,4.145409e+13,NaN,564532,0.6722
2005-01-25,HDFCBANK,EQ,491.35,525.00,539.40,492.10,522.00,520.60,505.64,1006248,5.088042e+13,NaN,641845,0.6379
2005-01-27,HDFCBANK,EQ,520.60,522.25,548.00,518.00,539.00,537.65,526.60,1211154,6.377884e+13,NaN,674695,0.5571
2005-01-28,HDFCBANK,EQ,537.65,537.65,548.80,527.25,537.00,539.85,536.74,487588,2.617064e+13,NaN,283862,0.5822
2005-01-31,HDFCBANK,EQ,539.85,536.50,570.00,535.00,570.00,564.60,552.91,667854,3.692614e+13,NaN,417341,0.6249
2005-02-01,HDFCBANK,EQ,564.60,566.00,568.75,550.25,561.00,560.15,558.31,386403,2.157329e+13,NaN,179337,0.4641
2005-02-02,HDFCBANK,EQ,560.15,564.95,564.95,553.00,555.95,558.60,557.36,230247,1.283308e+13,NaN,126081,0.5476
2005-02-03,HDFCBANK,EQ,558.60,559.00,575.00,557.00,575.00,573.50,570.90,404119,2.307099e+13,NaN,202437,0.5009
2005-02-04,HDFCBANK,EQ,573.50,570.00,579.00,563.05,565.25,567.15,571.33,178917,1.022204e+13,NaN,56482,0.3157
2005-02-07,HDFCBANK,EQ,567.15,565.25,575.00,552.05,553.60,561.75,565.17,120125,6.789115e+12,NaN,41930,0.3491
2005-02-08,HDFCBANK,EQ,561.75,558.00,575.00,557.05,575.00,570.45,566.11,175716,9.947450e+12,NaN,97164,0.5530
2005-02-09,HDFCBANK,EQ,570.45,572.00,589.90,570.00,582.25,588.10,583.61,301754,1.761056e+13,NaN,150159,0.4976
2005-02-10,HDFCBANK,EQ,588.10,590.00,590.00,575.10,578.60,579.50,579.10,170770,9.889262e+12,NaN,84733,0.4962
2005-02-11,HDFCBANK,EQ,579.50,579.95,579.95,568.00,576.00,575.00,572.95,243036,1.392473e+13,NaN,141033,0.5803
2005-02-14,HDFCBANK,EQ,575.00,562.40,578.25,562.40,569.00,568.65,572.21,312996,1.790998e+13,NaN,210769,0.6734
2005-02-15,HDFCBANK,EQ,568.65,575.00,578.00,560.10,560.10,562.50,565.08,317150,1.792164e+13,NaN,161584,0.5095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-11-20,HDFCBANK,EQ,1825.55,1829.00,1839.70,1829.00,1836.05,1838.15,1836.08,598106,1.098171e+14,30131.0,336543,0.5627
2017-11-21,HDFCBANK,EQ,1838.15,1837.45,1850.00,1836.10,1848.00,1846.25,1845.41,568883,1.049823e+14,17143.0,349608,0.6146
2017-11-22,HDFCBANK,EQ,1846.25,1849.70,1860.00,1844.55,1854.60,1855.25,1853.89,1415199,2.623629e+14,31420.0,944319,0.6673
2017-11-23,HDFCBANK,EQ,1855.25,1859.00,1860.00,1838.00,1840.00,1842.85,1847.79,808145,1.493279e+14,16903.0,492990,0.6100
2017-11-24,HDFCBANK,EQ,1842.85,1843.00,1857.80,1841.00,1857.50,1851.40,1848.31,1300921,2.404501e+14,26271.0,979768,0.7531
2017-11-27,HDFCBANK,EQ,1851.40,1849.00,1862.00,1845.60,1860.15,1857.55,1852.09,967618,1.792112e+14,75853.0,622801,0.6436
2017-11-28,HDFCBANK,EQ,1857.55,1856.00,1871.00,1855.85,1867.15,1865.35,1866.29,1272635,2.375105e+14,44306.0,921267,0.7239
2017-11-29,HDFCBANK,EQ,1865.35,1865.00,1875.50,1855.80,1873.00,1873.30,1869.11,818646,1.530143e+14,17331.0,476557,0.5821
2017-11-30,HDFCBANK,EQ,1873.30,1868.70,1873.95,1840.00,1852.75,1853.70,1859.89,1449078,2.695122e+14,37220.0,770804,0.5319
2017-12-01,HDFCBANK,EQ,1853.70,1854.90,1860.00,1844.10,1850.85,1848.20,1850.81,964537,1.785177e+14,39290.0,598556,0.6206
2017-12-04,HDFCBANK,EQ,1848.20,1854.90,1854.90,1830.10,1836.30,1834.10,1840.43,910483,1.675681e+14,36729.0,629502,0.6914
2017-12-05,HDFCBANK,EQ,1834.10,1826.00,1828.55,1807.00,1824.90,1820.45,1818.21,973340,1.769739e+14,30980.0,546351,0.5613
2017-12-06,HDFCBANK,EQ,1820.45,1819.95,1821.35,1799.00,1799.30,1803.30,1809.42,1598780,2.892867e+14,47014.0,1164494,0.7284
2017-12-07,HDFCBANK,EQ,1803.30,1806.65,1816.60,1803.10,1810.90,1809.65,1809.12,1057826,1.913737e+14,49113.0,626080,0.5919
2017-12-08,HDFCBANK,EQ,1809.65,1814.00,1853.00,1814.00,1842.25,1840.40,1839.43,2239100,4.118674e+14,38922.0,1482220,0.6620
2017-12-11,HDFCBANK,EQ,1840.40,1848.00,1851.75,1840.00,1846.40,1846.40,1846.99,799558,1.476775e+14,45584.0,490124,0.6130
2017-12-12,HDFCBANK,EQ,1846.40,1849.10,1849.90,1815.95,1818.00,1819.90,1826.78,602647,1.100901e+14,17546.0,315406,0.5234
2017-12-13,HDFCBANK,EQ,1819.90,1820.05,1845.00,1815.10,1821.40,1821.35,1832.20,726865,1.331764e+14,27628.0,270762,0.3725
2017-12-14,HDFCBANK,EQ,1821.35,1824.00,1840.00,1812.00,1837.10,1838.05,1826.18,920773,1.681497e+14,21825.0,441606,0.4796
2017-12-15,HDFCBANK,EQ,1838.05,1856.00,1888.00,1855.50,1871.00,1873.45,1877.73,3112531,5.844489e+14,68576.0,1845713,0.5930
2017-12-18,HDFCBANK,EQ,1873.45,1855.00,1899.00,1809.30,1878.40,1878.95,1876.25,3074497,5.768529e+14,46417.0,1558319,0.5069
2017-12-19,HDFCBANK,EQ,1878.95,1879.80,1893.65,1876.15,1886.95,1884.50,1884.02,1238028,2.332475e+14,34874.0,666370,0.5383
2017-12-20,HDFCBANK,EQ,1884.50,1898.90,1903.10,1863.65,1866.35,1868.15,1885.29,2335876,4.403801e+14,83598.0,1303739,0.5581
2017-12-21,HDFCBANK,EQ,1868.15,1879.90,1885.00,1865.20,1866.05,1868.30,1871.04,1713636,3.206288e+14,57272.0,1059344,0.6182
2017-12-22,HDFCBANK,EQ,1868.30,1879.00,1880.00,1861.75,1874.65,1876.65,1870.36,1117726,2.090554e+14,46791.0,609701,0.5455
2017-12-26,HDFCBANK,EQ,1876.65,1881.00,1882.80,1856.70,1870.00,1868.35,1867.60,1696424,3.168235e+14,23017.0,1186061,0.6992
2017-12-27,HDFCBANK,EQ,1868.35,1870.10,1870.30,1851.15,1852.50,1856.75,1863.90,872346,1.625968e+14,21881.0,569939,0.6533
2017-12-28,HDFCBANK,EQ,1856.75,1858.90,1880.90,1858.00,1870.05,1878.05,1873.07,2175130,4.074175e+14,42854.0,1373463,0.6314
2017-12-29,HDFCBANK,EQ,1878.05,1876.80,1879.20,1868.15,1871.40,1872.40,1873.42,1586468,2.972120e+14,29466.0,1059416,0.6678
2018-01-01,HDFCBANK,EQ,1872.40,1872.70,1880.75,1850.50,1855.00,1854.50,1862.24,1645129,3.063623e+14,30994.0,1222191,0.7429

In [21]:
#If index: df = get_history(symbol=a, start=date(2005,1,1), end=date(2018,1,1),index=True)
#If options: df = get_history(symbol=a,start=date(2005,1,1),end=date(2005,1,20),option_type="CE",strike_price=300,expiry_date=date(2005,1,29))